### ISSUE TITLE
Sleep modes?

### ISSUE THREAD

**Issue by Nereuxofficial** [plantineers/edge#3]
Saving power when the device is not in use for multiple minutes is very worthwhile. We could use the built-in sleep modes of the esp to wake it up after a time interval saving massive amounts of power. Also we could use rtc memory to store data that is persistent during even deep sleep.

Unfortunately light/deep sleep [doesn't seem supported in esp-hal yet](https://github.com/esp-rs/esp-hal/issues/375). We could also use esp-idf, which would no longer use the pure rust bindings.

**Comment by bjoernQ** [comment]
For inspiration

- https://github.com/bjoernQ/esp32c3-sleep-experiment
- https://matrix.to/#/!LdaNPfUfvefOLewEIM:matrix.org/$MGQY24t_Zo-eufQ6vFjUX99MLHOb7W41f9F44BwBHX8?via=matrix.org&via=tchncs.de&via=mozilla.org

**Comment by Nereuxofficial** [comment]
@bjoernQ Thanks for the inspiration! That will really help us implement this. 

Github delivered the email but the comment here seems to have been lost during the Github outages, so i'll take the liberty and quote it
>For inspiration
>
>https://github.com/bjoernQ/esp32c3-sleep-experiment
>https://matrix.to/#/!LdaNPfUfvefOLewEIM:matrix.org/$MGQY24t_Zo-eufQ6vFjUX99MLHOb7W41f9F44BwBHX8?via=matrix.org&via=tchncs.de&via=mozilla.org
